### ISSUE TITLE
Breaking change warning: changing name of ca350 to ca350.py

### ISSUE THREAD

**Issue by adorobis** [TimWeyand/homeassistant-addon#1]
Hi, 
I'm about to merge a pull request. I've added feature to support EWT sensors and controls and I've cleaned up a bit. So far working ok for a few weeks in my installation. There is only one breaking change: I've changed the main file name from ca350 to ca350.py which makes it a bit easier to work with :)
Hope not to much of a problem for you.

Adam

**Comment by TimWeyand** [comment]
Thanks for the Heads up 🙂 Fixed and an new Version is already build and works
